branches:
  only:
    - master
    - develop

language:
  - python

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

env:
  - USE_UVLOOP=0
  - USE_UVLOOP=1

install:
  - "pip install -r requirements.txt"
  - "pip install coverage coveralls pytest"
  - "if [[ $USE_UVLOOP == 1 ]]; then pip install uvloop; fi"

script:
  - "coverage run --source=stormsurge setup.py test"

after_success:
  - "python -m coveralls"