branches:
  only:
  - master
  - develop

language:
- python

python:
- '3.4'
- '3.5'
- '3.5-dev'
- nightly

install:
- pip install -r requirements.txt
- pip install coverage coveralls pytest

script:
- coverage run --source=stormhttp setup.py test

after_success:
- coveralls
